# Generated by Django 5.2.9 on 2025-12-10 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ThreatActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('first_seen', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IOC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=512, unique=True)),
                ('ioc_type', models.CharField(choices=[('IP', 'IP Address'), ('DOMAIN', 'Domain'), ('URL', 'URL'), ('HASH_MD5', 'MD5 Hash'), ('HASH_SHA256', 'SHA256 Hash'), ('EMAIL', 'Email Address')], max_length=20)),
                ('source', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('reputation_score', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('geo_country', models.CharField(blank=True, max_length=50, null=True)),
                ('asn', models.CharField(blank=True, max_length=50, null=True)),
                ('whois_data', models.JSONField(blank=True, default=dict)),
                ('virus_total_report', models.JSONField(blank=True, default=dict)),
                ('campaigns', models.ManyToManyField(blank=True, related_name='iocs', to='core.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=20)),
                ('status', models.CharField(default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('iocs', models.ManyToManyField(related_name='incidents', to='core.ioc')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='threat_actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='core.threatactor'),
        ),
    ]
